### PR TITLE
simplify implementation, remove encodeClassic etc

### PR DESCRIPTION
**Pull request by staltz**
Lots going on here:

- Removed `encodeClassic`, `encodeBendyButt` since they're not needed anymore
- Renamed a bunch of things as `tf` and `d` to reflect the parts T-F-D
- Named consts for each individual operation, for clarity

### CODE REVIEW

**Review by arj03 — APPROVED** [review]
Ah yes, now we are back to simple encode / decode like before the null change. The only thing I noticed in this PR is the NIL_TF name. In a way it is both a NIL_TF and NIL_TFD. And sometimes it would be more readable as NIL_TFD. Don't know what you think?

**Comment by staltz** [comment]
Yes I know what you mean, and was unsure what to do, because in practice there is no "D" bytes. But for clarity it might be better that we are returning the "whole" TFD, despite the D being useless.

PS: I renamed "NULL" to "NIL" to reflect that this is a primitive that has nothing to do with JS `null`, it's a cross-language concept, so I picked the name that Go uses.

**Comment by arj03** [comment]
Yeah that is what I'm thinking. 

I like the nil to signify that this is not a JS encoding :)

**Comment by arj03** [comment]
Excellent! Nice addition with the latest NIL_TFD change.

**Pull request merged**
